### ISSUE TITLE
Issues Encountered While Deploying CountGD with Docker

### ISSUE THREAD

**Issue by Applied-Energetic** [niki-amini-naieni/CountGD#24]
Hello,
I am encountering some issues when trying to create a Docker environment for CountGD using the following command:

`docker run -it -p 7860:7860 --platform=linux/amd64 --gpus all registry.hf.space/nikigoli-countgd:latest python app.py`

I would appreciate your help in resolving these issues. Below, I will provide the logs and details about my environment.

### environment：
win10
### docker version：
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### GPU
GPU：NVIDIA TITAN RTX
![image](https://github.com/user-attachments/assets/eb341aa3-ab7e-4d44-bf10-dd09405642fd)

### error log

2024-12-21 21:57:47 Processing ./gradio_image_prompter-0.1.0-py3-none-any.whl
2024-12-21 21:57:47 Requirement already satisfied: gradio<5.0,>=4.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio-image-prompter==0.1.0) (4.44.1)
2024-12-21 21:57:47 Requirement already satisfied: jinja2<4.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.1.4)
2024-12-21 21:57:47 Requirement already satisfied: urllib3~=2.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.2.3)
2024-12-21 21:57:47 Requirement already satisfied: aiofiles<24.0,>=22.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (23.2.1)
2024-12-21 21:57:47 Requirement already satisfied: pydub in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.25.1)
2024-12-21 21:57:47 Requirement already satisfied: anyio<5.0,>=3.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (4.6.2.post1)
2024-12-21 21:57:47 Requirement already satisfied: uvicorn>=0.14.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.32.0)
2024-12-21 21:57:47 Requirement already satisfied: numpy<3.0,>=1.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.1.2)
2024-12-21 21:57:47 Requirement already satisfied: python-multipart>=0.0.9 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.0.12)
2024-12-21 21:57:47 Requirement already satisfied: tomlkit==0.12.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.12.0)
2024-12-21 21:57:47 Requirement already satisfied: packaging in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (24.1)
2024-12-21 21:57:47 Requirement already satisfied: pyyaml<7.0,>=5.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (6.0.2)
2024-12-21 21:57:47 Requirement already satisfied: huggingface-hub>=0.19.3 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.26.1)
2024-12-21 21:57:47 Requirement already satisfied: gradio-client==1.3.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.3.0)
2024-12-21 21:57:47 Requirement already satisfied: orjson~=3.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.10.10)
2024-12-21 21:57:47 Requirement already satisfied: semantic-version~=2.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.10.0)
2024-12-21 21:57:47 Requirement already satisfied: typing-extensions~=4.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (4.12.2)
2024-12-21 21:57:47 Requirement already satisfied: typer<1.0,>=0.12 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.12.5)
2024-12-21 21:57:47 Requirement already satisfied: pandas<3.0,>=1.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.2.3)
2024-12-21 21:57:47 Requirement already satisfied: pillow<11.0,>=8.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (10.4.0)
2024-12-21 21:57:47 Requirement already satisfied: importlib-resources<7.0,>=1.3 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (6.4.5)
2024-12-21 21:57:47 Requirement already satisfied: fastapi<1.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.115.3)
2024-12-21 21:57:47 Requirement already satisfied: ffmpy in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.4.0)
2024-12-21 21:57:47 Requirement already satisfied: matplotlib~=3.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.9.2)
2024-12-21 21:57:47 Requirement already satisfied: ruff>=0.2.2 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.7.1)
2024-12-21 21:57:47 Requirement already satisfied: httpx>=0.24.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.27.2)
2024-12-21 21:57:47 Requirement already satisfied: pydantic>=2.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.9.2)
2024-12-21 21:57:47 Requirement already satisfied: markupsafe~=2.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.1.5)
2024-12-21 21:57:47 Requirement already satisfied: websockets<13.0,>=10.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio-client==1.3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (12.0)
2024-12-21 21:57:47 Requirement already satisfied: fsspec in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from gradio-client==1.3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2024.9.0)
2024-12-21 21:57:47 Requirement already satisfied: sniffio>=1.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.3.1)
2024-12-21 21:57:47 Requirement already satisfied: exceptiongroup>=1.0.2 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.2.2)
2024-12-21 21:57:47 Requirement already satisfied: idna>=2.8 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.10)
2024-12-21 21:57:47 Requirement already satisfied: starlette<0.42.0,>=0.40.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from fastapi<1.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.41.0)
2024-12-21 21:57:47 Requirement already satisfied: httpcore==1.* in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from httpx>=0.24.1->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.0.6)
2024-12-21 21:57:47 Requirement already satisfied: certifi in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from httpx>=0.24.1->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2024.8.30)
2024-12-21 21:57:47 Requirement already satisfied: h11<0.15,>=0.13 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.24.1->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.14.0)
2024-12-21 21:57:48 Requirement already satisfied: tqdm>=4.42.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from huggingface-hub>=0.19.3->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (4.66.5)
2024-12-21 21:57:48 Requirement already satisfied: requests in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from huggingface-hub>=0.19.3->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.32.3)
2024-12-21 21:57:48 Requirement already satisfied: filelock in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from huggingface-hub>=0.19.3->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.16.1)
2024-12-21 21:57:48 Requirement already satisfied: fonttools>=4.22.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (4.54.1)
2024-12-21 21:57:48 Requirement already satisfied: pyparsing>=2.3.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.2.0)
2024-12-21 21:57:48 Requirement already satisfied: python-dateutil>=2.7 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.9.0.post0)
2024-12-21 21:57:48 Requirement already satisfied: kiwisolver>=1.3.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.4.7)
2024-12-21 21:57:48 Requirement already satisfied: cycler>=0.10 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.12.1)
2024-12-21 21:57:48 Requirement already satisfied: contourpy>=1.0.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.3.0)
2024-12-21 21:57:48 Requirement already satisfied: tzdata>=2022.7 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2024.2)
2024-12-21 21:57:48 Requirement already satisfied: pytz>=2020.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2024.2)
2024-12-21 21:57:48 Requirement already satisfied: annotated-types>=0.6.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from pydantic>=2.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.7.0)
2024-12-21 21:57:48 Requirement already satisfied: pydantic-core==2.23.4 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from pydantic>=2.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.23.4)
2024-12-21 21:57:48 Requirement already satisfied: click>=8.0.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (8.0.4)
2024-12-21 21:57:48 Requirement already satisfied: rich>=10.11.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (13.9.3)
2024-12-21 21:57:48 Requirement already satisfied: shellingham>=1.3.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.5.4)
2024-12-21 21:57:48 Requirement already satisfied: six>=1.5 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (1.16.0)
2024-12-21 21:57:48 Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (2.18.0)
2024-12-21 21:57:48 Requirement already satisfied: markdown-it-py>=2.2.0 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.0.0)
2024-12-21 21:57:48 Requirement already satisfied: charset-normalizer<4,>=2 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from requests->huggingface-hub>=0.19.3->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (3.4.0)
2024-12-21 21:57:48 Requirement already satisfied: mdurl~=0.1 in /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio<5.0,>=4.0->gradio-image-prompter==0.1.0) (0.1.2)
2024-12-21 21:57:49 Installing collected packages: gradio-image-prompter
2024-12-21 21:57:49 Successfully installed gradio-image-prompter-0.1.0
2024-12-21 21:57:50 
2024-12-21 21:57:50 [notice] A new release of pip available: 22.3.1 -> 24.3.1
2024-12-21 21:57:50 [notice] To update, run: pip install --upgrade pip
2024-12-21 21:57:52 /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
2024-12-21 21:57:52   return torch._C._cuda_getDeviceCount() > 0
2024-12-21 21:57:52 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2024-12-21 21:57:52 inside get_extensions
2024-12-21 21:57:52 False
2024-12-21 21:57:52 /usr/local/cuda
2024-12-21 21:57:52 Traceback (most recent call last):
2024-12-21 21:57:52   File "/home/user/app/models/GroundingDINO/ops/setup.py", line 77, in <module>
2024-12-21 21:57:52     ext_modules=get_extensions(),
2024-12-21 21:57:52   File "/home/user/app/models/GroundingDINO/ops/setup.py", line 55, in get_extensions
2024-12-21 21:57:52     raise NotImplementedError('Cuda is not available')
2024-12-21 21:57:52 NotImplementedError: Cuda is not available
2024-12-21 21:57:53 Processing /home/user/app/models/GroundingDINO/ops
2024-12-21 21:57:55   Preparing metadata (setup.py) ... error
2024-12-21 21:57:55   error: subprocess-exited-with-error
2024-12-21 21:57:55   
2024-12-21 21:57:55   × python setup.py egg_info did not run successfully.
2024-12-21 21:57:55   │ exit code: 1
2024-12-21 21:57:55   ╰─> [14 lines of output]
2024-12-21 21:57:55       /home/user/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
2024-12-21 21:57:55         return torch._C._cuda_getDeviceCount() > 0
2024-12-21 21:57:55       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2024-12-21 21:57:55       inside get_extensions
2024-12-21 21:57:55       False
2024-12-21 21:57:55       /usr/local/cuda
2024-12-21 21:57:55       Traceback (most recent call last):
2024-12-21 21:57:55         File "<string>", line 2, in <module>
2024-12-21 21:57:55         File "<pip-setuptools-caller>", line 34, in <module>
2024-12-21 21:57:55         File "/home/user/app/models/GroundingDINO/ops/setup.py", line 77, in <module>
2024-12-21 21:57:55           ext_modules=get_extensions(),
2024-12-21 21:57:55         File "/home/user/app/models/GroundingDINO/ops/setup.py", line 55, in get_extensions
2024-12-21 21:57:55           raise NotImplementedError('Cuda is not available')
2024-12-21 21:57:55       NotImplementedError: Cuda is not available
2024-12-21 21:57:55       [end of output]
2024-12-21 21:57:55   
2024-12-21 21:57:55   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-12-21 21:57:55 error: metadata-generation-failed
2024-12-21 21:57:55 
2024-12-21 21:57:55 × Encountered error while generating package metadata.
2024-12-21 21:57:55 ╰─> See above for output.
2024-12-21 21:57:55 
2024-12-21 21:57:55 note: This is an issue with the package mentioned above, not pip.
2024-12-21 21:57:55 hint: See above for details.
2024-12-21 21:57:55 
2024-12-21 21:57:55 [notice] A new release of pip available: 22.3.1 -> 24.3.1
2024-12-21 21:57:55 [notice] To update, run: pip install --upgrade pip
2024-12-21 21:57:56 Traceback (most recent call last):
2024-12-21 21:57:56   File "/home/user/app/models/GroundingDINO/ops/./test.py", line 18, in <module>
2024-12-21 21:57:56     from functions.ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch
2024-12-21 21:57:56   File "/home/user/app/models/GroundingDINO/ops/functions/__init__.py", line 9, in <module>
2024-12-21 21:57:56     from .ms_deform_attn_func import MSDeformAttnFunction
2024-12-21 21:57:56   File "/home/user/app/models/GroundingDINO/ops/functions/ms_deform_attn_func.py", line 18, in <module>
2024-12-21 21:57:56     import MultiScaleDeformableAttention as MSDA
2024-12-21 21:57:56 ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'
2024-12-21 21:57:57 Traceback (most recent call last):
2024-12-21 21:57:57   File "/home/user/app/app.py", line 202, in <module>
2024-12-21 21:57:57     model, transform = build_model_and_transforms(args)
2024-12-21 21:57:57   File "/home/user/app/app.py", line 184, in build_model_and_transforms
2024-12-21 21:57:57     from models.registry import MODULE_BUILD_FUNCS
2024-12-21 21:57:57   File "/home/user/app/models/__init__.py", line 7, in <module>
2024-12-21 21:57:57     from .GroundingDINO import build_groundingdino
2024-12-21 21:57:57   File "/home/user/app/models/GroundingDINO/__init__.py", line 15, in <module>
2024-12-21 21:57:57     from .groundingdino import build_groundingdino
2024-12-21 21:57:57   File "/home/user/app/models/GroundingDINO/groundingdino.py", line 55, in <module>
2024-12-21 21:57:57     from .transformer import build_transformer
2024-12-21 21:57:57   File "/home/user/app/models/GroundingDINO/transformer.py", line 28, in <module>
2024-12-21 21:57:57     from .ms_deform_attn import MultiScaleDeformableAttention as MSDeformAttn
2024-12-21 21:57:57   File "/home/user/app/models/GroundingDINO/ms_deform_attn.py", line 31, in <module>
2024-12-21 21:57:57     import MultiScaleDeformableAttention as _C
2024-12-21 21:57:57 ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

![image](https://github.com/user-attachments/assets/a17bc665-689a-4fa7-9d36-8cb46b3021dc)

 I am unsure how to modify the command or configuration to correctly set up the environment within Docker. I would appreciate any suggestions on how to properly configure the environment for CountGD in Docker.

Thank you for your assistance.

**Comment by IMG-PRCSNG** [comment]
Hi @Applied-Energetic,

Quick question - could you please post the output of the following command from your system to help debug this? From the logs, it looks like a library inside the container coulnd't find the cuda runtime libraries.


```bash
docker run --rm -it -p 7860:7860 --platform=linux/amd64 --gpus all registry.hf.space/nikigoli-countgd:latest /bin/bash -c 'nvidia-smi && which nvcc'
```

**Comment by Applied-Energetic** [comment]
Sure, I will run the command you provided, and the output is as follows:

![image](https://github.com/user-attachments/assets/df11412f-4a05-4a0d-ae01-39c895c17902)

Based on the results, it seems that the issue lies with my Docker during the CUDA installation.

![image](https://github.com/user-attachments/assets/06bf46fd-7cb0-429b-a278-e84f9d7043ee)

So, could you provide some suggestions to complete the Docker installation?

I would appreciate any assistance in resolving this issue.

Thank you for your help.

**Comment by IMG-PRCSNG** [comment]
Thanks for your response and for sharing the output.

Does the following print `True` on your machine?

```bash
docker run -it -p 7860:7860 --platform=linux/amd64 --gpus all registry.hf.space/nikigoli-countgd:latest python -c 'import torch; print(torch.cuda.is_available())'
```

If it prints `False`, then there seems to be a weird issue where the torch library inside docker is not able to find the cuda runtime libraries. Once you confirm, I will share a fix / workaround for the moment.

**Comment by Applied-Energetic** [comment]
Thank you for your response. The output is as follows, showing false.


![image](https://github.com/user-attachments/assets/37f2fa86-4f60-407b-9850-117459af3f06)

**Comment by IMG-PRCSNG** [comment]
Hi,

I have raise a [PR](https://huggingface.co/spaces/nikigoli/countgd/discussions/3) with a fix to the huggingfaces repo. Once it gets merged, the docker image will be updated and you can use it.

Meanwhile, if you would like to try to build the image locally,

```
git clone https://huggingface.co/spaces/nikigoli/countgd
cd countgd && git fetch origin refs/pr/3:pr/3
git checkout pr/3
docker build --platform=linux/amd64 -t countgd:latest .

# To run
docker run -it -p 7860:7860 --platform=linux/amd64 --gpus all countgd:latest
```

Cheers!

**Comment by Applied-Energetic** [comment]
Thank you sincerely for your assistance and the time you have spent on this. I will try it immediately after the repository is updated and provide feedback on the results

**Comment by niki-amini-naieni** [comment]
The pull request has been merged. You can now try the app and let us know if it works for you with the changes. Thank you @IMG-PRCSNG for your very helpful and useful contribution!!!🥇

**Comment by niki-amini-naieni** [comment]
Has this been resolved?
